<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>ir.av</groupId>
    <artifactId>tms</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>tms</name>

    <modules>
        <module>core</module>
        <module>adapters</module>
        <module>application-delivery</module>
        <module>container</module>
    </modules>


    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>
            <dependency>
                <groupId>org.testcontainers</groupId>
                <artifactId>testcontainers-bom</artifactId>
                <version>1.21.3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>core-domain</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>core-application-ports-inbound</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>core-application-ports-outbound</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>core-application-usecases</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>adapters-secondary-persistence</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>adapters-primary-rest-api</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>adapters-secondary-redis</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>ir.av.tms</groupId>
                <artifactId>application-delivery</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <properties>

        <revision>1.0.0</revision>

        <!-- Java -->
        <java.version>21</java.version>
        <maven.compiler.release>${java.version}</maven.compiler.release>

        <spring-boot.version>3.5.14</spring-boot.version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>

        <!-- Encoding -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <maven-clean-plugin.version>3.3.2</maven-clean-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>

        <maven-surefire-plugin.version>3.5.3</maven-surefire-plugin.version>
        <maven-failsafe-plugin.version>3.5.3</maven-failsafe-plugin.version>

        <maven-jar-plugin.version>3.4.2</maven-jar-plugin.version>
        <maven-war-plugin.version>3.4.0</maven-war-plugin.version>

        <maven-install-plugin.version>3.1.4</maven-install-plugin.version>
        <maven-deploy-plugin.version>3.1.4</maven-deploy-plugin.version>

        <maven-source-plugin.version>3.3.1</maven-source-plugin.version>
        <maven-javadoc-plugin.version>3.11.2</maven-javadoc-plugin.version>

        <maven-enforcer-plugin.version>3.6.1</maven-enforcer-plugin.version>

    </properties>

    <build>

        <pluginManagement>

            <plugins>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven-clean-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>

                    <configuration>
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>

                    <configuration>

                        <release>${maven.compiler.release}</release>

                        <encoding>${project.build.sourceEncoding}</encoding>

                        <parameters>true</parameters>

                        <compilerArgs>
                            <arg>-Xlint:all</arg>
                        </compilerArgs>

                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>

                    <configuration>

                        <useModulePath>false</useModulePath>

                        <includes>
                            <include>**/*Test.java</include>
                            <include>**/*Tests.java</include>
                        </includes>

                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>${maven-failsafe-plugin.version}</version>

                    <configuration>

                        <includes>
                            <include>**/*IT.java</include>
                            <include>**/*IntegrationTest.java</include>
                        </includes>

                    </configuration>

                    <executions>
                        <execution>
                            <id>integration-tests</id>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>

                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>${maven-jar-plugin.version}</version>

                    <configuration>

                        <archive>
                            <manifest>
                                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                            </manifest>
                        </archive>

                    </configuration>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>${maven-war-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-install-plugin</artifactId>
                    <version>${maven-install-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-deploy-plugin</artifactId>
                    <version>${maven-deploy-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven-source-plugin.version}</version>

                    <executions>
                        <execution>
                            <id>attach-sources</id>
                            <phase>verify</phase>
                            <goals>
                                <goal>jar-no-fork</goal>
                            </goals>
                        </execution>
                    </executions>

                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>${maven-javadoc-plugin.version}</version>
                </plugin>

                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${maven-enforcer-plugin.version}</version>

                    <executions>

                        <execution>
                            <id>enforce-java-and-maven</id>
                            <phase>validate</phase>

                            <goals>
                                <goal>enforce</goal>
                            </goals>

                            <configuration>

                                <rules>

                                    <!-- Java 21 -->
                                    <requireJavaVersion>
                                        <version>[21,22)</version>
                                    </requireJavaVersion>

                                    <!-- Maven 3.9+ -->
                                    <requireMavenVersion>
                                        <version>[3.9,)</version>
                                    </requireMavenVersion>

                                </rules>

                            </configuration>

                        </execution>

                    </executions>

                </plugin>

            </plugins>

        </pluginManagement>

    </build>

</project>
