spring:
  datasource:
    url: jdbc:postgresql://tms-postgres:5432/tms
    username: tms
    password: tms
    driver-class-name: org.postgresql.Driver

    hikari:
      pool-name: AccountHikariPool
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 3000
      validation-timeout: 1000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
  threads:
    virtual:
      enabled: true
server:
  tomcat:
    max-connections: 20000
    accept-count: 10000